### ISSUE TITLE
port to 2.96

### ISSUE THREAD

**Issue by sancheolz** [ivalkeen/rhythmbox-vkontakte#3]
На версии плеера от 2.95-2.96(других не было под рукой) работает только после удаления полностью методов do_impl_get_status(self) и do_get_status(self). В этой версии do_get_status(self) принимает 4 параметра(на гите ритмбокса есть исходник плагина magnatune - там можно подсмотреть), но даже подстановка правильных параметров не спасает: теперь у Source класса нет массива(списка) searches и других. 
Где можно посмотреть члены и методы класса Source? Да и вообще документацию к нему?
И что-то плагин через раз ищет

**Comment by ivalkeen** [comment]
Документации, я так понимаю, нет в природе вообще, сам разбирался по исходникам ритмбокса + документации по PyGTK. Но вообще, я в своем форке только правил немного оригинальный плагин Алексея, чтобы он работал на версии 2.90.1, это год назад где-то было.

Ребята из ритмбокса ломают API в каждой новой версии, а времени и желания каждый раз переписывать этот плагин у меня пока нету (у Алексея похоже тоже).

**Comment by sancheolz** [comment]
Вот это был фейл. 2 часа искал переменную current_search в исходниках ритмбокса, а она оказалась локальной, да к тому же не до конца вырезанной;) Так, что можно удалить весь блок за if self.current_search: и заработает на 2.95-2.96

**Comment by sancheolz** [comment]
вот патч для этого

``` diff
*** VkontakteSource.py  2012-08-22 11:14:42.000000000 +0400
--- VkontakteSource.py.my   2012-11-17 12:17:33.279656649 +0400
***************
*** 27,33 ****
      self.entry_view = entry_view

      search_entry = Gtk.Entry()
-     search_entry.set_width_chars(100)
      search_entry.set_activates_default(True)

      self.search_entry = search_entry
--- 27,32 ----
***************
*** 39,45 ****
      self.search_button = search_button

      hbox = Gtk.HBox()
!     hbox.pack_start(search_entry, False, False, 0)
      hbox.pack_start(search_button, False, False, 5)

      vbox = Gtk.VBox()
--- 38,44 ----
      self.search_button = search_button

      hbox = Gtk.HBox()
!     hbox.pack_start(search_entry, True, True, 0)
      hbox.pack_start(search_button, False, False, 5)

      vbox = Gtk.VBox()
***************
*** 64,74 ****
        self.initialise()
      self.search_button.grab_default()

!   # rhyhtmbox api break up (0.13.2 - 0.13.3)
!   def do_impl_get_status(self):
!     return self.do_get_status()
! 
!   def do_get_status(self):
      if self.error_msg:
        error_msg = self.error_msg
        self.error_msg = ''
--- 63,69 ----
        self.initialise()
      self.search_button.grab_default()

!   def do_get_status(self, status, progress_text, progress):
      if self.error_msg:
        error_msg = self.error_msg
        self.error_msg = ''
***************
*** 84,95 ****
        if self.download_queue:
          str += " (%s files more in queue)" % len(self.download_queue)
        return (str, "", progress)
-     if self.current_search:
-       if self.searches[self.current_search].is_complete():
-         return (self.props.query_model.compute_status_normal("Found %d result", "Found %d results"), "", 1)
-       else:
-         return ("Searching for \"{0}\"".format(self.current_search), "", -1)
- 
      else:
        return ("", "", 1)

--- 79,84 ----
```

подправил гуи немного
Вот только написан плагин для Апи контакта 2.0- может из-за этого он и выдает иногда пустой список музыки. Заняться переписыванием что ли? Благо есть хороший и рабочий пример в foobnix, только возьму версию от  grunichev с сохранением всего ее функионала. Тоже интересно разобраться, что там в гтк валится из-за чего не удалось портировать плагин на Peas

**Comment by ivalkeen** [comment]
Если получится - будет здорово.
